namespace ClipDeck.Core;

public static partial class Loc
{
    static readonly Dictionary<string, string> English = new()
    {
        // formats
        ["{0:N0} karakter"] = "{0:N0} characters",
        ["{0:N0} öğe · {1:N1} MB"] = "{0:N0} items · {1:N1} MB",
        ["{0} dk önce"] = "{0} min ago",
        ["{0} öğe"] = "{0} items",
        ["{0} öğe geri yüklendi, {1} öğe zaten vardı."] = "{0} items restored, {1} were already there.",
        ["{0} öğe seçili · Enter birleştirip yapıştırır · Esc seçimi temizler"] = "{0} selected · Enter pastes them together · Esc clears the selection",
        ["{0} panoya kopyalandı."] = "{0} copied to the clipboard.",
        ["{0} sa önce"] = "{0} h ago",
        ["az önce"] = "just now",
        ["dün {0}"] = "yesterday {0}",

        // popup
        ["Ara"] = "Search",
        ["Ara — resimlerdeki yazılar dahil"] = "Search — text inside images too",
        ["Pano geçmişi"] = "Clipboard history",
        ["Geçmiş"] = "History",
        ["Sabitli"] = "Pinned",
        ["Snippet"] = "Snippets",
        ["Emoji"] = "Emoji",
        ["Kaomoji"] = "Kaomoji",
        ["Semboller"] = "Symbols",
        ["Ayarlar"] = "Settings",
        ["Ten rengi"] = "Skin tone",
        ["Filtrele"] = "Filter",
        ["Uygulama"] = "App",
        ["Yeni snippet"] = "New snippet",
        ["Kaydı duraklat"] = "Pause recording",
        ["Kayda devam et"] = "Resume recording",
        ["Ctrl + rakam ile hızlı yapıştır"] = "Quick paste with Ctrl + number",
        ["Enter yapıştır · Shift+Enter düz metin · Ctrl+Space çoklu seç · Sağ tık menü"] = "Enter paste · Shift+Enter plain · Ctrl+Space select · Right-click menu",
        ["Enter ekle · Shift+Enter ekle, açık kalsın · Oklarla gez · Tab bölüm"] = "Enter insert · Shift+Enter insert and keep open · Arrows move · Tab section",
        ["Enter ekle · Shift+Enter ekle, açık kalsın"] = "Enter insert · Shift+Enter insert and keep open",
        ["Eşleşen sonuç yok."] = "No matches.",
        ["Bu filtreye uyan öğe yok."] = "Nothing matches this filter.",
        ["Henüz bir şey kopyalanmadı.\nBir şey kopyala, burada görünsün."] = "Nothing copied yet.\nCopy something and it shows up here.",
        ["Sabitlenmiş öğe yok.\nBir öğede Ctrl+P ile sabitle."] = "No pinned items.\nPin one with Ctrl+P.",
        ["Snippet yok.\n+ ile yeni ekle ya da bir öğede Ctrl+S."] = "No snippets.\nAdd one with + or press Ctrl+S on an item.",
        ["Bu bölümde gösterilecek bir şey yok."] = "Nothing to show here.",
        ["Yükleniyor…"] = "Loading…",
        ["Veri yüklenemedi."] = "Could not load the data.",
        ["Yapıştır"] = "Paste",
        ["Düz metin olarak yapıştır"] = "Paste as plain text",
        ["Dönüştür ve yapıştır"] = "Transform and paste",
        ["Sadece panoya kopyala"] = "Copy to clipboard only",
        ["Metni çıkar (OCR)"] = "Extract text (OCR)",
        ["Sabitle"] = "Pin",
        ["Sabitlemeyi kaldır"] = "Unpin",
        ["Snippet olarak kaydet"] = "Save as snippet",
        ["Snippet düzenle"] = "Edit snippet",
        ["Düzenle"] = "Edit",
        ["Sil"] = "Delete",
        ["Silindi."] = "Deleted.",
        ["Sabitlendi — temizlikte silinmez."] = "Pinned — it survives clean-ups.",
        ["Sabitleme kaldırıldı."] = "Unpinned.",
        ["Metin çıkarılıyor…"] = "Extracting text…",
        ["Resimde okunabilir metin bulunamadı."] = "No readable text in this image.",
        ["Metin çıkarıldı — Enter ile yapıştır."] = "Text extracted — press Enter to paste.",
        ["Kayıt duraklatıldı."] = "Recording paused.",
        ["Kayıt duraklatıldı — kopyalananlar kaydedilmiyor."] = "Recording paused — copies are not saved.",
        ["Kayıt devam ediyor."] = "Recording resumed.",
        ["Panoya kopyalandı"] = "Copied to the clipboard",
        ["Ctrl+V ile yapıştırabilirsin."] = "Paste it with Ctrl+V.",
        ["Panoya yazılamadı."] = "Could not write to the clipboard.",
        ["gizli"] = "hidden",
        ["Son kullanılanlar"] = "Recently used",

        // filters
        ["Tümü"] = "All",
        ["Metin"] = "Text",
        ["Link"] = "Links",
        ["Resim"] = "Images",
        ["Dosya"] = "Files",
        ["Kod"] = "Code",
        ["Renk kodu"] = "Colour codes",
        ["Gizli"] = "Sensitive",

        // skin tones
        ["Varsayılan"] = "Default",
        ["Açık"] = "Light",
        ["Orta açık"] = "Medium-light",
        ["Orta"] = "Medium",
        ["Orta koyu"] = "Medium-dark",
        ["Koyu"] = "Dark",

        // emoji groups
        ["Yüzler ve duygular"] = "Smileys & emotion",
        ["İnsanlar ve vücut"] = "People & body",
        ["Hayvanlar ve doğa"] = "Animals & nature",
        ["Yiyecek ve içecek"] = "Food & drink",
        ["Seyahat ve yerler"] = "Travel & places",
        ["Etkinlikler"] = "Activities",
        ["Nesneler"] = "Objects",
        ["Bayraklar"] = "Flags",
        ["Emoji ara (Türkçe ya da İngilizce)"] = "Search emoji (English or Turkish)",

        // kaomoji categories
        ["Kaomoji ara"] = "Search kaomoji",
        ["Mutlu"] = "Happy",
        ["Sevgi"] = "Love",
        ["Üzgün"] = "Sad",
        ["Kızgın"] = "Angry",
        ["Şaşkın"] = "Surprised",
        ["Selam"] = "Greeting",
        ["Omuz silkme"] = "Shrug",
        ["Masa fırlatma"] = "Table flip",
        ["Hayvanlar"] = "Animals",
        ["Diğer"] = "Other",

        // symbol categories
        ["Sembol ara (Türkçe kategori ya da İngilizce ad)"] = "Search symbols by name or category",
        ["Noktalama"] = "Punctuation",
        ["Para birimi"] = "Currency",
        ["Matematik"] = "Math",
        ["Üst ve alt simge"] = "Superscript & subscript",
        ["Oklar"] = "Arrows",
        ["Yunan harfleri"] = "Greek letters",
        ["Latin harfleri"] = "Latin letters",
        ["İşaretler"] = "Signs",
        ["Şekiller"] = "Shapes",
        ["Kutu çizimi"] = "Box drawing",

        // text transforms
        ["BÜYÜK HARF"] = "UPPER CASE",
        ["küçük harf"] = "lower case",
        ["Başlık Düzeni"] = "Title Case",
        ["Boşlukları temizle"] = "Clean up whitespace",
        ["Tek satıra indir"] = "Join into one line",
        ["Satırları sırala"] = "Sort lines",
        ["Tekrarlayan satırları sil"] = "Remove duplicate lines",
        ["JSON güzelleştir"] = "Pretty-print JSON",
        ["JSON sıkıştır"] = "Minify JSON",
        ["URL kodla"] = "URL encode",
        ["URL çöz"] = "URL decode",
        ["Base64 kodla"] = "Base64 encode",
        ["Base64 çöz"] = "Base64 decode",
        ["Geçerli bir JSON değil."] = "Not valid JSON.",
        ["Geçerli bir Base64 değil."] = "Not valid Base64.",
        ["Çözülen veri metin değil."] = "The decoded data is not text.",
        ["Dönüştürülemedi: "] = "Could not transform: ",

        // manager
        ["Öğe okunamadı."] = "Could not read the item.",
        ["Bu öğede metin yok."] = "This item has no text.",
        ["Seçilen öğelerde metin yok."] = "The selected items have no text.",
        ["Pano şu an başka bir uygulamada kilitli, tekrar dene."] = "Another app is holding the clipboard, try again.",

        // snippet window
        ["Başlık"] = "Title",
        ["İçerik"] = "Content",
        ["İçerik boş olamaz."] = "Content cannot be empty.",
        ["Değişkenler (yapıştırırken doldurulur): "] = "Variables (filled in when pasted): ",
        ["Kaydet"] = "Save",
        ["İptal"] = "Cancel",

        // settings
        ["clipdeck ayarları"] = "clipdeck settings",
        ["Genel"] = "General",
        ["Win+V'yi devral"] = "Take over Win+V",
        ["Kapalıyken Windows'un kendi pano paneli açılır; clipdeck'i tepsi simgesinden açarsın."] = "When off, Windows opens its own clipboard panel; open clipdeck from the tray icon.",
        ["Win+. ile emoji panelini aç"] = "Open the emoji panel with Win+.",
        ["Windows açılınca başlat"] = "Start with Windows",
        ["Yapıştırdığım öğeyi listenin en üstüne taşı"] = "Move pasted items to the top",
        ["Yönetici olarak çalıştır"] = "Run as administrator",
        ["Yönetici olarak açılmış programlara da yapıştırabilmek için. Açılışta UAC onayı istenir; otomatik başlatma zamanlanmış görevle, onaysız yapılır."] = "Lets clipdeck paste into programs running as administrator. A UAC prompt appears when started by hand; start-up with Windows uses a scheduled task without a prompt.",
        ["%{0:0}"] = "{0:0}%",
        ["Yeni sürümleri denetle"] = "Check for new versions",
        ["Şimdi denetle"] = "Check now",
        ["Açıksa günde bir kez GitHub'dan yalnızca en son sürümün numarasını okur; senden hiçbir bilgi gönderilmez."] = "When on, clipdeck reads only the latest version number from GitHub once a day; nothing about you is sent.",
        ["Denetleniyor…"] = "Checking…",
        ["clipdeck güncel ({0})."] = "clipdeck is up to date ({0}).",
        ["clipdeck {0} çıktı; sen {1} kullanıyorsun. Sürüm sayfası açılsın mı?"] = "clipdeck {0} is out; you have {1}. Open the release page?",
        ["Güncelleme denetlenemedi: "] = "Could not check for updates: ",
        ["Yeni sürüm: {0}"] = "New version: {0}",
        ["clipdeck {0} çıktı"] = "clipdeck {0} is out",
        ["İndirmek için tıkla."] = "Click to download.",
        ["Dil"] = "Language",
        ["Görünüm"] = "Appearance",
        ["Tema"] = "Theme",
        ["Sistem"] = "System",
        ["Vurgu rengi"] = "Accent colour",
        ["Sistem rengi"] = "System colour",
        ["Özel: "] = "Custom: ",
        ["Özel…"] = "Custom…",
        ["Arka plan"] = "Background",
        ["Fotoğraf seç…"] = "Choose photo…",
        ["Kaldır"] = "Remove",
        ["Bulanıklık"] = "Blur",
        ["Karartma"] = "Dimming",
        ["Kart opaklığı"] = "Card opacity",
        ["Panel genişliği"] = "Panel width",
        ["Panel yüksekliği"] = "Panel height",
        ["Arka plan fotoğrafı seç"] = "Choose a background photo",
        ["Resimler"] = "Images",
        ["Tüm dosyalar"] = "All files",
        ["Bu dosya resim olarak açılamadı."] = "This file could not be opened as an image.",
        ["Yok — düz renk"] = "None — solid colour",
        ["Seçili fotoğraf"] = "Current photo",
        ["Fotoğraf kaydedilemedi: "] = "Could not save the photo: ",
        ["Kayıt"] = "Recording",
        ["Resimleri kaydet"] = "Save images",
        ["Resimlerdeki yazıyı otomatik oku (OCR)"] = "Read text in images automatically (OCR)",
        ["Ekran görüntüsündeki yazılar aramada bulunur. Windows'un yerleşik OCR'ı kullanılır, internet gerekmez."] = "Text in screenshots becomes searchable. Uses the OCR built into Windows, no internet needed.",
        ["Dosya kopyalamalarını kaydet"] = "Save copied files",
        ["Geçmiş sınırı"] = "History limit",
        ["öğe  (0 = sınırsız)"] = "items  (0 = unlimited)",
        ["Otomatik silme"] = "Auto delete",
        ["günden eski öğeler  (0 = kapalı)"] = "days and older  (0 = off)",
        ["Sabitlenen öğeler ve snippet'ler bu sınırlara dahil değildir, hiç silinmez."] = "Pinned items and snippets are never counted or deleted.",
        ["Geçmiş sınırı 0 ya da pozitif bir sayı olmalı."] = "The history limit must be 0 or a positive number.",
        ["Otomatik silme süresi 0 ya da pozitif bir gün sayısı olmalı."] = "Auto delete must be 0 or a positive number of days.",
        ["Gizlilik"] = "Privacy",
        ["Şifre yöneticilerinin \"kaydetme\" işaretine uy"] = "Respect the \"do not save\" flag from password managers",
        ["KeePass, Bitwarden, 1Password gibi uygulamalar kopyaladıkları şifreleri işaretler; bu öğeler geçmişe hiç yazılmaz."] = "Apps like KeePass, Bitwarden and 1Password mark the passwords they copy; those are never written to history.",
        ["Kart numarası, IBAN, şifre ve anahtar gibi hassas veriler"] = "Sensitive data such as card numbers, IBANs, passwords and keys",
        ["Maskele"] = "Mask",
        ["Hiç kaydetme"] = "Don't save",
        ["Normal göster"] = "Show normally",
        ["Maskelenen öğeler listede •••• 1234 gibi görünür ve aramada çıkmaz; yapıştırınca tam hali gider."] = "Masked items show as •••• 1234 and are left out of search; pasting still inserts the full value.",
        ["Hiç kaydedilmeyecek uygulamalar (her satıra bir işlem adı)"] = "Apps that are never recorded (one process name per line)",
        ["Geçmiş AES-256-GCM ile şifreli tutulur; anahtar yalnızca bu Windows hesabıyla açılabilir (DPAPI)."] = "History is encrypted with AES-256-GCM; the key only opens under this Windows account (DPAPI).",
        ["Veri"] = "Data",
        ["Yedekle…"] = "Back up…",
        ["Geri yükle…"] = "Restore…",
        ["Klasörü aç"] = "Open folder",
        ["Geçmişi temizle"] = "Clear history",
        ["Yedek, kendi parolanla şifrelenmiş tek bir dosyadır; başka bir bilgisayara taşıyıp geri yükleyebilirsin."] = "A backup is a single file encrypted with your own password; move it to another PC and restore it there.",
        ["Kısayollar"] = "Shortcuts",
        ["Kapat"] = "Close",
        ["yönetici"] = "administrator",
        ["Sabitlenmemiş tüm geçmiş silinsin mi?\nSabitli öğeler ve snippet'ler kalır. Bu işlem geri alınamaz."] = "Delete all unpinned history?\nPinned items and snippets stay. This cannot be undone.",
        ["Yönetici modu için clipdeck yeniden başlatılmalı (UAC onayı istenecek). Şimdi yeniden başlatılsın mı?"] = "clipdeck needs to restart for administrator mode (a UAC prompt will appear). Restart now?",
        ["Dil değişikliği yeniden başlatınca uygulanır. Şimdi yeniden başlatılsın mı?"] = "The language changes after a restart. Restart now?",
        ["clipdeck bir sonraki açılışta normal modda çalışacak."] = "clipdeck will run in normal mode from the next start.",
        ["Win+V pano · Win+. emoji · yaz ara · Tab bölüm değiştir (Geçmiş → Sabitli → Snippet → Emoji → Kaomoji → Semboller)"] =
            "Win+V clipboard · Win+. emoji · type to search · Tab switches section (History → Pinned → Snippets → Emoji → Kaomoji → Symbols)",
        ["Pano: ↑↓ seç · Enter yapıştır · Shift+Enter düz metin · Space / F3 önizleme · Ctrl+Space / Ctrl+tık çoklu seç · Ctrl+1…9 hızlı yapıştır · Ctrl+P sabitle · Ctrl+S snippet yap · Ctrl+E snippet düzenle · Ctrl+O resimden metin · Ctrl+C sadece kopyala · Del sil · Menü tuşu / Shift+F10 menü"] =
            "Clipboard: ↑↓ select · Enter paste · Shift+Enter plain text · Space / F3 preview · Ctrl+Space / Ctrl+click multi-select · Ctrl+1…9 quick paste · Ctrl+P pin · Ctrl+S make snippet · Ctrl+E edit snippet · Ctrl+O text from image · Ctrl+C copy only · Del delete · Menu key / Shift+F10 menu",
        ["Snippet değişkenleri: "] = "Snippet variables: ",
        ["Emoji / Kaomoji / Semboller: oklarla gez · Enter ekle · Shift+Enter ekle ve panel açık kalsın · Esc kapat"] =
            "Emoji / Kaomoji / Symbols: arrows move · Enter insert · Shift+Enter insert and keep the panel open · Esc close",

        ["clipdeck geçmişini yeni biçime taşıyor. Büyük geçmişlerde bu bir dakika sürebilir, lütfen bekle…"] = "clipdeck is upgrading your history to a new format. With a large history this can take a minute, please wait…",

        // preview & link cleaning
        ["Space / F3 kapatır"] = "Space / F3 closes",
        ["Space / F3 önizlemeyi kapatır · Shift+↑↓ kaydırır"] = "Space / F3 closes the preview · Shift+↑↓ scrolls",
        ["Önizle"] = "Preview",
        ["Önizleme açılamadı."] = "Could not open the preview.",
        ["Gizli öğe"] = "Sensitive item",
        ["Bu öğe hassas veri içeriyor; önizlemede maskeli gösterilir. Yapıştırınca tam hali gider."] = "This item contains sensitive data, so the preview stays masked. Pasting still inserts the full value.",
        ["Resim · {0}×{1}"] = "Image · {0}×{1}",
        ["Resimdeki yazı:"] = "Text in the image:",
        ["{0} dosya"] = "{0} files",
        ["Link · {0}"] = "Link · {0}",
        ["İzleme parametreleri olmadan:"] = "Without tracking parameters:",
        ["Kod · {0} satır"] = "Code · {0} lines",
        ["Metin · {0:N0} karakter · {1} satır"] = "Text · {0:N0} characters · {1} lines",
        ["Uzun metin: ilk {0:N0} karakter gösteriliyor."] = "Long text: showing the first {0:N0} characters.",
        ["Klasör"] = "Folder",
        ["Artık yok"] = "No longer exists",
        ["İzleme parametrelerini temizleyip yapıştır"] = "Paste without tracking parameters",
        ["Linklerdeki izleme parametreleri (utm_, fbclid, gclid…)"] = "Tracking parameters in links (utm_, fbclid, gclid…)",
        ["Otomatik temizle"] = "Clean automatically",
        ["Menüden"] = "From the menu",
        ["Kapalı"] = "Off",
        ["Otomatik: tek başına kopyalanan link panoda da temizlenir. Menüden: sağ tık menüsünde \"temizleyip yapıştır\" seçeneği çıkar."] = "Automatic: a link copied on its own is cleaned on the clipboard too. From the menu: the right-click menu offers \"paste without tracking parameters\".",

        // backup
        ["Yedeği şifrele"] = "Encrypt backup",
        ["Yedek bu parolayla şifrelenir. Parolayı unutursan yedek açılamaz."] = "The backup is encrypted with this password. If you forget it, the backup cannot be opened.",
        ["Yedeği kaydet"] = "Save backup",
        ["clipdeck yedeği"] = "clipdeck backup",
        ["Yedek kaydedildi: {0} öğe."] = "Backup saved: {0} items.",
        ["Yedekleniyor…"] = "Backing up…",
        ["Geri yükleniyor…"] = "Restoring…",
        ["Yedek kaydedilemedi: "] = "Could not save the backup: ",
        ["Yedeği aç"] = "Open backup",
        ["Yedeği oluştururken kullandığın parolayı gir."] = "Enter the password you used for this backup.",
        ["Yedek açılamadı: "] = "Could not open the backup: ",
        ["Bu dosya bir clipdeck yedeği değil."] = "This file is not a clipdeck backup.",
        ["Yedek dosyası bozuk."] = "The backup file is damaged.",
        ["Parola yanlış ya da dosya bozuk."] = "Wrong password or damaged file.",
        ["Parola"] = "Password",
        ["Parola (tekrar)"] = "Password (again)",
        ["Parola en az 8 karakter olmalı."] = "The password must be at least 8 characters.",
        ["Parolalar aynı değil."] = "The passwords do not match.",
        ["Parola gir."] = "Enter a password.",
        ["Tamam"] = "OK",

        // app, tray, welcome
        ["clipdeck çalışıyor"] = "clipdeck is running",
        ["Win+V ile aç."] = "Open it with Win+V.",
        ["Tepsi simgesine tıklayarak aç."] = "Open it from the tray icon.",
        ["Aç  (Win+V)"] = "Open  (Win+V)",
        ["Çıkış"] = "Exit",
        ["clipdeck — kayıt duraklatıldı"] = "clipdeck — recording paused",
        ["Şifreleme anahtarı açılamadı (farklı Windows hesabı ya da bozuk dosya).\nEski dosyalar \".bozuk-…\" uzantısıyla kenara alındı, yeni ve boş bir geçmiş başlatıldı."] = "The encryption key could not be opened (different Windows account or damaged file).\nThe old files were set aside with a \".bozuk-…\" extension and a new, empty history was started.",
        ["Geçmiş veritabanı açılamadı.\nEski dosya \".bozuk-…\" uzantısıyla kenara alındı, yeni bir geçmiş başlatıldı."] = "The history database could not be opened.\nThe old file was set aside with a \".bozuk-…\" extension and a new history was started.",
        ["clipdeck'e hoş geldin"] = "Welcome to clipdeck",
        ["Kopyaladığın her şey artık tek bir yerde."] = "Everything you copy, in one place.",
        ["Win+V pano geçmişini, Win+. emojileri açar. Yazarak ara, Enter ile yapıştır."] = "Win+V opens your clipboard history, Win+. opens emoji. Type to search, press Enter to paste.",
        ["Win+V'yi devral (Windows pano paneli yerine clipdeck açılır)"] = "Take over Win+V (clipdeck opens instead of the Windows clipboard panel)",
        ["Bunları sonra Ayarlar'dan değiştirebilirsin."] = "You can change these later in Settings.",
        ["Başla"] = "Get started",

        // setup
        ["clipdeck kurulumu"] = "clipdeck setup",
        ["clipdeck'i kur"] = "Install clipdeck",
        ["clipdeck'i güncelle"] = "Update clipdeck",
        ["clipdeck'i kaldır"] = "Uninstall clipdeck",
        ["Kur"] = "Install",
        ["Güncelle"] = "Update",
        ["Kuruluyor…"] = "Installing…",
        ["Kaldırılıyor…"] = "Uninstalling…",
        ["Pano geçmişi, emoji, kaomoji ve semboller"] = "Clipboard history, emoji, kaomoji and symbols",
        ["Kurulacak yer: {0}"] = "Install location: {0}",
        ["Başlat menüsüne kısayol ekle"] = "Add a Start menu shortcut",
        ["Masaüstüne kısayol ekle"] = "Add a desktop shortcut",
        ["Kurulumdan sonra başlat"] = "Start after installing",
        ["Yönetici izni gerekmez; yalnızca bu Windows kullanıcısı için kurulur. Geçmişin ve ayarların korunur."] = "No administrator rights needed; installs for this Windows user only. Your history and settings are kept.",
        ["clipdeck bu bilgisayardan kaldırılacak: program dosyaları, kısayollar ve otomatik başlatma silinir."] = "clipdeck will be removed from this PC: program files, shortcuts and start-up entry are deleted.",
        ["Geçmişi, snippet'leri ve ayarları da sil"] = "Also delete history, snippets and settings",
        ["Kurulum tamamlandı."] = "Installation complete.",
        ["clipdeck güncellendi."] = "clipdeck updated.",
        ["clipdeck çalışıyor; Win+V ile açabilirsin."] = "clipdeck is running; open it with Win+V.",
        ["Başlat menüsünden açabilirsin."] = "Open it from the Start menu.",
        ["clipdeck kaldırıldı."] = "clipdeck was uninstalled.",
        ["Geçmiş ve ayarlar da silindi."] = "History and settings were deleted too.",
        ["Geçmiş ve ayarlar şurada duruyor: {0}"] = "History and settings are still in: {0}",
        ["İşlem tamamlanamadı: "] = "Could not finish: ",
        ["clipdeck — pano geçmişi, emoji ve semboller"] = "clipdeck — clipboard history, emoji and symbols",
    };
}
